#!/usr/bin/env ruby
require "nokogiri"

filename = ARGV.first

unless filename
  puts "USAGE: ./xml2csv input.xml > output.csv"
  exit(1)
end

doc = Nokogiri::XML(open(filename))
selector = "//machine/display"

puts "name;description;year;manufacturer;width;height;rotate"
doc.xpath(selector).each do |el|
  machine = el.parent
  rom = machine["romof"]
  name = machine["name"]
  description = machine.xpath("description").text
  year = machine.xpath("year").text
  manufacturer = machine.xpath("manufacturer").text

  display = machine.at_xpath("display")
  width = display["width"]
  height = display["height"]
  rotate = display["rotate"]

  # skip clone roms
  puts "#{name};#{description};#{year};#{manufacturer};#{width};#{height};#{rotate}" if rom.nil? || rom.empty?
end
